#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'


cookbook 'rax-mysql-tunables',
 :git => 'git@github.com:zainengineer/rax-mysql-tunables.git'

cookbook 'rax-wordpress',
   :git => 'git@github.com:zainengineer/rax-wordpress-cookbook.git'

cookbook 'vsftpd',
   :git => 'git@github.com:TheSerapher/chef-vsftpd.git'

